# Generated by Django 4.2.5 on 2024-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workingtime_end_time_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookanappointment',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
