# Generated by Django 4.2.5 on 2024-09-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bookanappointment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='end_time_pm',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
