# Generated by Django 4.2.5 on 2024-09-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workingtime_end_time_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookanappointment',
            options={'ordering': ['day', 'hour']},
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='day',
            field=models.CharField(choices=[('1', 'الأحد'), ('2', 'الإثنين'), ('3', 'الثلاثاء'), ('4', 'الأربعاء'), ('5', 'الخميس'), ('6', 'الجمعة'), ('7', 'السبت')], max_length=20),
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.FileField(upload_to='flows/')),
                ('trigger', models.ManyToManyField(to='api.trigger')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flow'),
        ),
    ]
