# Generated by Django 4.2.5 on 2024-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trigger_alter_bookanappointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='flow',
        ),
        migrations.AddField(
            model_name='client',
            name='flow',
            field=models.ManyToManyField(to='api.flow'),
        ),
    ]
