# Generated by Django 4.2.5 on 2024-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_client_flow_client_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='key',
            field=models.CharField(default='skdjhf23y98odgkashfdl', max_length=255, unique=True),
        ),
    ]
