# Generated by Django 4.2.5 on 2024-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calendar_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
