# Generated by Django 4.2.5 on 2024-09-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_calendar_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.flow'),
        ),
    ]
