# Generated by Django 4.2.5 on 2024-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chat_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookanappointment',
            name='patient',
            field=models.CharField(default='ali', max_length=50),
        ),
    ]
