# Generated by Django 4.2.5 on 2024-10-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_nexttime_nexttenday'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexttenday',
            name='day_end',
            field=models.DateField(default='2024-05-5'),
        ),
    ]
