# Generated by Django 4.2.5 on 2024-10-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_nexttenday_day_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='end_appointment',
            field=models.DateField(default='2024-11-10'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_appointment',
            field=models.DateField(default='2024-11-10'),
        ),
    ]
