# Generated by Django 5.1.3 on 2024-11-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_customuser_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='channle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.channle'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contact'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('pending', 'pending')], default='open', max_length=20),
        ),
    ]
