# Generated by Django 5.1.3 on 2024-11-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_conversation_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
