# Generated by Django 5.1.3 on 2024-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_contact_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser1',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('agent', 'agent')], max_length=20, null=True),
        ),
    ]
