# Generated by Django 5.1.3 on 2024-11-14 07:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_customuser1_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser1',
            name='team_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 7, 45, 36, 425400, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 7, 46, 18, 390134, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ManyToManyField(to='api.customuser1'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('complated', 'complated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='Reposts'),
        ),
    ]
