# Generated by Django 5.1.3 on 2025-02-08 08:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channle',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 8, 8, 0, 7, 338270, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
