# Generated by Django 5.1.3 on 2025-02-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_channle_updated_at_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channle',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='channle',
            name='phone_number_id',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
