# Generated by Django 5.1.3 on 2025-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_channle_updated_at_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='from_message',
            field=models.CharField(default='bot', max_length=30),
        ),
    ]
