# Generated by Django 5.1.3 on 2025-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_channle_phone_number_channle_phone_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_key',
            field=models.CharField(default='123', max_length=500),
        ),
    ]
