# Generated by Django 5.1.3 on 2025-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_chatmessage_from_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='channle',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='channle',
            name='phone_number_id',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='channle',
            name='tocken',
            field=models.TextField(default='123456454321', max_length=600),
        ),
    ]
