# Generated by Django 5.1.3 on 2025-02-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_channle_phone_number_channle_phone_number_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser1',
            options={'verbose_name_plural': 'Custom Usre'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customuser1'),
        ),
    ]
