# Generated by Django 5.1.3 on 2025-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_customuser1_options_alter_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
