# Generated by Django 5.1.3 on 2025-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_chatmessage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='channle',
            name='organization_id',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='channle',
            name='phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='channle',
            name='phone_number_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='channle',
            name='tocken',
            field=models.TextField(max_length=600),
        ),
    ]
