# Generated by Django 5.1.3 on 2025-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_internalchat_user_id_alter_chatmessage_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='user_id',
            new_name='members',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_user',
            field=models.CharField(choices=[('admin', 'admin'), ('sub-admin', 'sub-admin'), ('agent', 'agent')], default='admin', max_length=20),
        ),
    ]
