# Generated by Django 5.1.3 on 2025-06-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_account_options_rename_user_id_team_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_chatBotBuilder', 'Can Access ChatBot Builder'), ('can_access_channels', 'Can Access Channels'), ('can_access_team_members', 'Can Access Team Members')]},
        ),
    ]
