# Generated by Django 5.1.3 on 2025-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'imgage'), ('video', 'video'), ('document', 'document'), ('audio', 'audio'), ('template', 'template')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mediamanagement',
            name='file_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('image', 'imgage'), ('video', 'video'), ('document', 'document'), ('audio', 'audio'), ('template', 'template')], max_length=25, null=True),
        ),
    ]
