# Generated by Django 5.2.4 on 2025-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_chatmessage_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('pending', 'pending'), ('lock', 'lock')], default='open', max_length=20),
        ),
    ]
