# Generated by Django 5.2.4 on 2025-08-17 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_chatBotBuilder', 'Can Access ChatBot Builder'), ('can_access_channels', 'Can Access Channels'), ('can_access_team_members', 'Can Access Team Members'), ('can reassign for all chat', 'can reassign for all chat'), ('can reassign one chat', 'can reassign one chat'), ('can not reassign', 'can not reassign'), ('visibility all conversations', 'visibility all conversations'), ('visibility assigned conversations', 'visibility assigned conversations')]},
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
