# Generated by Django 5.2.4 on 2025-08-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_customuser_options_conversation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='restartkeyword',
            name='client',
        ),
        migrations.DeleteModel(
            name='MessageChat',
        ),
        migrations.RemoveField(
            model_name='nexttenday',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='nexttime',
            name='chat',
        ),
        migrations.AddField(
            model_name='channle',
            name='flows',
            field=models.ManyToManyField(to='api.flow'),
        ),
        migrations.AddField(
            model_name='chat',
            name='channel_id',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.channle'),
        ),
        migrations.AddField(
            model_name='restartkeyword',
            name='channel_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='restart_keyword', to='api.channle'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='NextTenDay',
        ),
        migrations.DeleteModel(
            name='NextTime',
        ),
    ]
