# Generated by Django 5.2.4 on 2025-08-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_client_flow_remove_chat_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_name',
            field=models.CharField(default='flow_1', max_length=100),
        ),
    ]
