# Generated by Django 5.2.4 on 2025-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_flow_flow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.CharField(blank=True, default='start_bot', max_length=100, null=True),
        ),
    ]
