# Generated by Django 5.2.4 on 2025-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(blank=True, choices=[('end_bot', 'end_bot'), ('start_bot', 'start_bot')], default='start_bot', max_length=100, null=True),
        ),
    ]
