# Generated by Django 5.2.4 on 2025-09-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channle',
            name='flows',
            field=models.ManyToManyField(blank=True, to='api.flow'),
        ),
    ]
