# Generated by Django 5.2.4 on 2025-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_channle_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='trigger',
            field=models.ManyToManyField(blank=True, to='api.trigger'),
        ),
    ]
