# Generated by Django 5.1.3 on 2026-01-22 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_parameter_api_whatsappcampaign_delete_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parameter',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.api'),
        ),
    ]
