# Generated by Django 5.1.3 on 2026-01-25 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_api_parameters_parameter_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='trigger',
        ),
        migrations.AddField(
            model_name='flow',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flow'),
        ),           
    ]
