# Generated by Django 5.1.3 on 2026-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('in_progress', 'in_progress'), ('review', 'review'), ('pending', 'pending'), ('onhold', 'onhold'), ('dependency', 'dependency'), ('lock', 'lock')], default='open', max_length=20),
        ),
    ]
