# Generated by Django 5.1.3 on 2026-02-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='failed_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='sent_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('ongoing', 'ongoing'), ('completed', 'Completed'), ('failed', 'Failed')], default='ongoing', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalyticsCamaign',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_message', models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('failed', 'failed'), ('pending', 'pending')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.whatsappcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contact')),
            ],
        ),
    ]
