# Generated by Django 5.1.3 on 2026-02-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_whatsappcampaign_failed_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalyticsCamaign',
            new_name='AnalyticsCampaign',
        ),
    ]
