# Generated by Django 5.1.3 on 2026-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_analyticscamaign_analyticscampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='flow_name',
            field=models.CharField(max_length=100),
        ),
    ]
