# Generated by Django 5.1.3 on 2026-03-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_flow_flow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='attribute',
            field=models.ManyToManyField(to='api.attribute'),
        ),
        migrations.AddField(
            model_name='api',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chat'),
        ),
    ]
