# Generated by Django 5.1.3 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='attribute',
        ),
        migrations.AddField(
            model_name='api',
            name='parameters',
            field=models.ManyToManyField(related_name='api_parameter', to='api.parameter'),
        ),
    ]
