# Generated by Django 5.1.3 on 2026-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_api_attribute_api_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
