# Generated by Django 5.1.3 on 2026-05-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_chatmessage_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flow'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(blank=True, choices=[('end_bot', 'end_bot'), ('start_bot', 'start_bot'), ('live_chat', 'live_chat')], default='start_bot', max_length=100, null=True),
        ),
    ]
