# Generated by Django 5.1.3 on 2026-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_chat_flow_alter_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='apiKey',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
