# Generated by Django 5.1.3 on 2026-05-03 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_account_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('apilog_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api')),
            ],
        ),
    ]
