# Generated by Django 5.1.3 on 2026-05-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_apilog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='api',
            name='tocken',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='api',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='key',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value',
        ),
        migrations.AlterField(
            model_name='api',
            name='parameters',
            field=models.ManyToManyField(related_name='api_param', to='api.parameter'),
        ),
        migrations.CreateModel(
            name='Api_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_param', models.CharField(blank=True, choices=[('parameter', 'parameter'), ('header', 'header')], max_length=50, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='parameters_new',
            field=models.ManyToManyField(through='api.Api_parameter', to='api.parameter'),
        ),
    ]
