# Generated by Django 5.1.3 on 2026-05-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_remove_api_headers_remove_api_tocken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='parameters',
        ),
    ]
