# Generated by Django 5.1.3 on 2026-05-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_api_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='parameters_new',
            new_name='parameters',
        ),
    ]
