# Generated by Django 5.1.3 on 2026-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_customuser_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='status_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
