# Generated by Django 5.1.3 on 2026-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_api_status_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='status_request',
        ),
        migrations.AddField(
            model_name='apilog',
            name='status_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
