# Generated by Django 5.1.3 on 2026-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_api_status_request_apilog_status_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
