# Generated by Django 5.1.3 on 2026-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_api_body_alter_api_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
