# Generated by Django 5.1.3 on 2026-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_chatmessage_media_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='save_api',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False'),
        ),
    ]
