# Generated by Django 5.1.3 on 2026-05-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_attribute_save_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='chat',
        ),
        migrations.CreateModel(
            name='Custome_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('variable', models.CharField(blank=True, max_length=50, null=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.api')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attribute')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='chat',
            field=models.ManyToManyField(through='api.Custome_attribute', to='api.chat'),
        ),
    ]
