# Generated by Django 5.1.3 on 2026-05-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_attribute_value_remove_attribute_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
