# Generated by Django 5.1.3 on 2026-05-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_attribute_value_remove_attribute_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custome_attribute',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.api'),
        ),
        migrations.AlterField(
            model_name='custome_attribute',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chat'),
        ),
    ]
