# Generated by Django 6.0.5 on 2026-05-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_attribute_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_chatBotBuilder', 'Can Access ChatBot Builder'), ('can_access_channels', 'Can Access Channels'), ('can_access_team_members', 'Can Access Team Members'), ('can reassign for all chat', 'can reassign for all chat'), ('can reassign for own chat', 'can reassign for own chat'), ('can not reassign', 'can not reassign'), ('visibility all conversations', 'visibility all conversations'), ('visibility assigned conversations', 'visibility assigned conversations')]},
        ),
    ]
