# Generated by Django 6.0.5 on 2026-05-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_chatBotBuilder', 'Can Access ChatBot Builder'), ('can_access_channels', 'Can Access Channels'), ('can_access_team_members', 'Can Access Team Members'), ('can_reassign_for_all_chat', 'can reassign for all chat'), ('can_reassign_for_own_chat', 'can reassign for own chat'), ('can_not_reassign', 'can not reassign'), ('visibility_all_conversations', 'visibility all conversations'), ('visibility_assigned_conversations', 'visibility assigned conversations'), ('can_access_developer', 'can access developer')]},
        ),
    ]
