# Generated by Django 6.0.5 on 2026-06-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_parameter',
            old_name='type_param',
            new_name='type',
        ),
    ]
