# Generated by Django 6.0.5 on 2026-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_rename_type_param_api_parameter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='error_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
