# Generated by Django 6.0.5 on 2026-07-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_chatmessage_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
