# Generated by Django 6.0.5 on 2026-07-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_flow_flow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='flow_id',
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateBoxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=100)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flow')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template')),
                ('template_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.templatebox')),
            ],
        ),
        migrations.AddField(
            model_name='templatebox',
            name='template_buttons',
            field=models.ManyToManyField(through='api.TemplateBoxTemplate', to='api.template'),
        ),
    ]
