# Generated by Django 6.0.5 on 2026-07-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_flow_flow_id_template_templatebox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
