# Generated by Django 6.0.5 on 2026-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_template_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channle',
            name='organization_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
