# Generated by Django 6.0.5 on 2026-09-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_channle_organization_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('can_create_account', 'Can create account'), ('can_edit_account', 'Can edit account'), ('can_delete_account', 'Can delete account'), ('can_view_account', 'Can view account')]},
        ),
        migrations.AlterModelOptions(
            name='api',
            options={'permissions': [('can_create_api', 'Can create API'), ('can_edit_api', 'Can edit API'), ('can_delete_api', 'Can delete API'), ('can_view_api', 'Can view API')]},
        ),
        migrations.AlterModelOptions(
            name='channle',
            options={'permissions': [('can_create_channle', 'Can create channle'), ('can_edit_channle', 'Can edit channle'), ('can_delete_channle', 'Can delete channle'), ('can_view_channle', 'Can view channle')]},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('can_create_contact', 'Can create contact'), ('can_edit_contact', 'Can edit contact'), ('can_delete_contact', 'Can delete contact'), ('can_view_contact', 'Can view contact')]},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'permissions': [('can_create_flow', 'Can create flow'), ('can_edit_flow', 'Can edit flow'), ('can_delete_flow', 'Can delete flow'), ('can_view_flow', 'Can view flow'), ('can_set_default_flow', 'Can set default flow')]},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('can_create_team', 'Can create team'), ('can_edit_team', 'Can edit team'), ('can_delete_team', 'Can delete team'), ('can_view_team', 'Can view team'), ('can_manage_team_members', 'Can manage team members')]},
        ),
    ]
