# Generated by Django 6.0.5 on 2026-09-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_account_options_alter_api_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='api',
            options={},
        ),
        migrations.AlterModelOptions(
            name='channle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
