# Generated by Django 6.0.5 on 2026-09-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_alter_account_options_alter_api_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_reassign_for_all_chat', 'can reassign for all chat'), ('can_reassign_for_own_chat', 'can reassign for own chat'), ('can_not_reassign', 'can not reassign'), ('visibility_all_conversations', 'visibility all conversations'), ('visibility_assigned_conversations', 'visibility assigned conversations')]},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'permissions': [('can_set_default_flow', 'Can set default flow')]},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('can_manage_team_members', 'Can manage team members')]},
        ),
    ]
