# Generated by Django 6.0.5 on 2026-09-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_customuser_options_alter_flow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('can_view_apikey', 'Can view apikey')]},
        ),
    ]
