# Generated by Django 6.0.5 on 2026-09-20 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tag'),
        ),
    ]
