# Generated by Django 6.0.5 on 2026-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_group_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channle',
            name='organization_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='channle',
            name='phone_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='channle',
            name='phone_number_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='channle',
            name='tocken',
            field=models.TextField(max_length=600, unique=True),
        ),
    ]
